name: Setup toolchains for cross compilation and cross testing for Rust
description: GitHub Action for setup toolchains for cross compilation and cross testing for Rust

inputs:
  target:
    description: Target name
    required: true
  runner:
    description: Test runner
    required: false

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/main.sh
      shell: bash
